### ISSUE TITLE
BUG: SoraEditor crashes in old android devices

### ISSUE THREAD

**Issue by CyberGlitch01** [TS-Code-Editor/Android-Code-Editor#1]
**Describe the bug**

**To Reproduce**
1. Go to Setting
2. Choose Sora editor
3. Open file in editor

SoraEditor is crashing in older devices but not in new device.

**Comment by TechnicalStudioDeveloper** [comment]
It is sora code editor bug which is fixed in [this commit](https://github.com/Rosemoe/sora-editor/commit/6ecaba9da7b85ea5921713dd578b84c0953d3c4d).
When sora editor library release it will be fixed.

**Comment by CyberGlitch01** [comment]
I tried with the latest Library but not fixed.

**Comment by CyberGlitch01** [comment]
```java.lang.NoClassDefFoundError: org.eclipse.tm4e.core.internal.utils.ObjectCloner$$ExternalSyntheticLambda2
	at org.eclipse.tm4e.core.internal.utils.ObjectCloner.deepClone(ObjectCloner.java:80)
	at org.eclipse.tm4e.core.internal.utils.ObjectCloner.deepClone(ObjectCloner.java:47)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.initGrammar(Grammar.java:244)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.<init>(Grammar.java:99)
	at org.eclipse.tm4e.core.internal.registry.SyncRegistry.grammarForScopeName(SyncRegistry.java:119)
	at org.eclipse.tm4e.core.registry.Registry._grammarForScopeName(Registry.java:221)
	at org.eclipse.tm4e.core.registry.Registry.addGrammar(Registry.java:196)
	at io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry.doLoadGrammar(GrammarRegistry.java:230)
	at io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry.loadGrammar(GrammarRegistry.java:192)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.prepareLoad(TextMateLanguage.java:105)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:120)
	at editor.tsd.editors.SoraEditor.initLanguageMode(SoraEditor.java:121)
	at editor.tsd.editors.SoraEditor.setLanguageMode(SoraEditor.java:79)
	at editor.tsd.widget.CodeEditorLayout.setLanguageMode(CodeEditorLayout.java:140)
	at android.code.editor.activity.CodeEditorActivity.openFileInEditor(CodeEditorActivity.java:469)
	at android.code.editor.activity.CodeEditorActivity.lambda$fileTree$5(CodeEditorActivity.java:430)
	at android.code.editor.activity.CodeEditorActivity.$r8$lambda$xlHUij2IVgQ2xGLphrxTS43NyOE(CodeEditorActivity.java)
	at android.code.editor.activity.CodeEditorActivity$$ExternalSyntheticLambda5.onClick(D8$$SyntheticClass)
	at android.view.View.performClick(View.java:5721)
	at android.view.View$PerformClick.run(View.java:22620)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7331)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)```

**Comment by CyberGlitch01** [comment]
```
java.lang.NoClassDefFoundError: org.eclipse.tm4e.core.internal.utils.ObjectCloner$$ExternalSyntheticLambda2
	at org.eclipse.tm4e.core.internal.utils.ObjectCloner.deepClone(ObjectCloner.java:80)
	at org.eclipse.tm4e.core.internal.utils.ObjectCloner.deepClone(ObjectCloner.java:47)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.initGrammar(Grammar.java:244)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.<init>(Grammar.java:99)
	at org.eclipse.tm4e.core.internal.registry.SyncRegistry.grammarForScopeName(SyncRegistry.java:119)
	at org.eclipse.tm4e.core.registry.Registry._grammarForScopeName(Registry.java:221)
	at org.eclipse.tm4e.core.registry.Registry.addGrammar(Registry.java:196)
	at io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry.doLoadGrammar(GrammarRegistry.java:230)
	at io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry.loadGrammar(GrammarRegistry.java:192)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.prepareLoad(TextMateLanguage.java:105)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:120)
	at editor.tsd.editors.SoraEditor.initLanguageMode(SoraEditor.java:121)
	at editor.tsd.editors.SoraEditor.setLanguageMode(SoraEditor.java:79)
	at editor.tsd.widget.CodeEditorLayout.setLanguageMode(CodeEditorLayout.java:140)
	at android.code.editor.activity.CodeEditorActivity.openFileInEditor(CodeEditorActivity.java:469)
	at android.code.editor.activity.CodeEditorActivity.lambda$fileTree$5(CodeEditorActivity.java:430)
	at android.code.editor.activity.CodeEditorActivity.$r8$lambda$xlHUij2IVgQ2xGLphrxTS43NyOE(CodeEditorActivity.java)
	at android.code.editor.activity.CodeEditorActivity$$ExternalSyntheticLambda5.onClick(D8$$SyntheticClass)
	at android.view.View.performClick(View.java:5721)
	at android.view.View$PerformClick.run(View.java:22620)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7331)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by DevVigilante** [comment]
Desugaring...
